apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspectsofyou-endpoint
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: aspectsofyou-endpoint
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: aspectsofyou-endpoint
    spec:
      containers:
        - name: aspectsofyou-endpoint
          image: "{{ .Values.image }}-endpoint:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: aspectsofyou-secret
          {{- if .Values.azure }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/etc/secrets"
              readOnly: true
          {{- end }}

      {{- if .Values.azure }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aspectsofyou-secretproviderclass"
      {{- end }}