version: 2
updates:
  - package-ecosystem: npm
    directory: /admin/frontend
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "next"
          - "eslint-config-next"
          - "react"
          - "react-dom"
          - "@mui/*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /aspectsofyou-endpoint
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /aspectsofyou-endpoint
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /admin/frontend
    schedule:
      interval: monthly
