version: '3.8'
services:
  webapi:
    build: .
    ports:
      - "5059:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__AspectContext=Host=postgres;Database=aspects;Username=strawberry;Password=strawberry

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=strawberry
      - POSTGRES_PASSWORD=strawberry
      - POSTGRES_DB=aspects
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strawberry -d aspects"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: