hostname: aspectsofyou.local
ingressClass: nginx

backend:
  image: fnwicr.azurecr.io/aspectsofyou-endpoint
  tag: latest
  replicas: 1
  port: 8080
  env:
    - name: ASPNETCORE_URLS
      value: "http://+:80"
    - name: Cors__AllowedOrigins
      value: "https://aspectsofyou.datanose.nl"


frontend:
  image: fnwicr.azurecr.io/aspectsofyou-frontend
  tag: latest
  replicas: 1
  port: 3000

azure:
  enabled: false
  keyvaultName: keyvaultName
  resourceGroup: resourceGroupName
  subscriptionId: subscriptionId
  tenantId: tenantId
  clientId: clientId
  identityName: identityName
  secrets:
    - name: "aspectsofyou-surfconext-secret"
      key: SurfConext__ClientSecret
    - name: "aspectsofyou-connectionstring"
      key: ConnectionStrings__AspectContext