// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UvA.AspectsOfYou.Endpoint.Entities;

#nullable disable

namespace UvA.AspectsOfYou.Endpoint.Migrations
{
    [DbContext(typeof(AspectContext))]
    [Migration("20260128074728_AddDisplaySlots")]
    partial class AddDisplaySlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Answer", b =>
                {
                    b.Property<Guid>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExtraText")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.DisplaySlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ViewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("ViewId");

                    b.ToTable("DisplaySlots");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Response", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Additional")
                        .HasColumnType("text");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.HasKey("ResponseId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Survey", b =>
                {
                    b.Property<Guid>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Editing")
                        .HasColumnType("boolean");

                    b.Property<bool>("Live")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SurveyId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreateSurveys")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewAnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ViewQuestionId");

                    b.ToTable("ViewAnswerOptions");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExcludedAnswerIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedResponseIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExcludedFromView")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderingId")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewSurveyId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ViewTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("ViewType");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ViewSurveyId");

                    b.ToTable("ViewQuestions");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FunkyBackground")
                        .HasColumnType("boolean");

                    b.Property<bool>("FunkyColors")
                        .HasColumnType("boolean");

                    b.Property<bool>("FunkyFont")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("ViewSurveys");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Answer", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.DisplaySlot", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId");

                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.ViewSurvey", "ViewSurvey")
                        .WithMany()
                        .HasForeignKey("ViewId");

                    b.Navigation("Survey");

                    b.Navigation("ViewSurvey");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Question", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Response", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Answer", "Answer")
                        .WithMany("Responses")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewAnswerOption", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.ViewQuestion", "ViewQuestion")
                        .WithMany("ViewAnswerOptions")
                        .HasForeignKey("ViewQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("ViewQuestion");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewQuestion", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.ViewSurvey", "ViewSurvey")
                        .WithMany("ViewQuestions")
                        .HasForeignKey("ViewSurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("ViewSurvey");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewSurvey", b =>
                {
                    b.HasOne("UvA.AspectsOfYou.Endpoint.Entities.Survey", "Survey")
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Answer", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewQuestion", b =>
                {
                    b.Navigation("ViewAnswerOptions");
                });

            modelBuilder.Entity("UvA.AspectsOfYou.Endpoint.Entities.ViewSurvey", b =>
                {
                    b.Navigation("ViewQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
